message:
    prefix:
        info: "&b&l[ i ]&b "
        success: "&2&l[ \u2714 ]&2 "
        warn: "&6&l[ ! ]&6 "
        error: "&4&l[ \u2715 ]&4 "
        announce: "&5&l[ ! ]&5 "

motd:
    title: "&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■ &e&lSTEMCRAFT &3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■&3■&b■"
    text: "Welcome to Minecraft"
    show-version: true

hub:
    world: "world"
    tp-commands:
        bw_amazon:
            - "bw leave"
            - "teleport {hub-world} {player}"

chat-format: "<{prefix}{name}{suffix}> {message}"

recipes:
    remove: []
    stonecutter:
        cobblestone:
            gravel: 2

gamemode-inventories:
    # keep this many inventories per player/gamemode/world
    max-count: 50

# Number of days after which unvisited chunks are regenerated
chunk-regenerate-delay: 56

private-server:
    enabled: false
    password: "cats"

item-lore:
    - toolstats

trader:
    name: Trader
    
    # check for trader every x ticks
    spawn-update: 6000

    # chance a trader will be spawned
    spawn-chance: 0.2

    # despawn trader when all players are this far away
    despawn-distance: 128
    
    # seconds per block a trade is available from its initial traded location
    trade-delay-per-block: 0.6

    # seconds before a trade is available across any dimensions/worlds
    trade-delay-between-worlds: 14400

    # seconds before a trade will always be available
    trade-delay-force-available: 86400

    # worlds a trader can be spawned
    worlds:
        - world
        - world_nether
        - world_the_end

skip-night:
    required: 0.25
    worlds:
        - survival

character-bindings:
    crafting_table: "\uE120"
    enchantment_table: "\uE121"
    skeleton_head_front: "\uE122"
    chat_bubble: "\uE123"
    info_purple: "\uE124"
    info_blue: "\uE125"
    info_green: "\uE126"
    question_yellow: "\uE127"
    question_bluE: "\uE128"
    question_green: "\uE129"
    world: "\uE12a"
    location: "\uE12b"
    house: "\uE12c"
    purple_bed: "\uE12d"
    green_bed: "\uE12e"
    discord: "\uE12f"
    warning_yellow: "\uE131"
    warning_red: "\uE132"
    click_action_left: "\uE133"
    click_action_right: "\uE134"
    chest: "\uE135"

custom_items:
    "stemcraft:copper_coin":
        item: "minecraft:stick"
        display_name: "Copper Coin"
        custom_model_data: 10000